base_url = "https://maravexa.com"
title = "MaraVexa"
description = "Personal site of Mara Vexa"
default_language = "en"
compile_sass = false
generate_feeds = true
feed_filenames = ["rss.xml"]
minify_html = true

[markdown]
smart_punctuation = true

[markdown.highlighting]
highlight_code = true
light_theme = "github-light"
dark_theme = "github-dark"

[[taxonomies]]
name = "tags"
feed = true

[extra]
author       = "Mara Vexa"
author_title = "Security Engineer"
author_email = "me@maravexa.com"
author_github = "https://github.com/maravexa"
